//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ak_Bars_Galeryyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newcollection
    {
        public int NewCollection_Id { get; set; }
        public string Photo { get; set; }
        public int Artist_Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
